gradle/libs.versions.toml
phone/core/navigation/build.gradle.kts
wear/core/navigation/build.gradle.kts

navController2.8.1を追加しました
https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=81305832
build.gradleにnavigationを追加

navigation2.8.1をimplementation

---

gradle/libs.versions.toml

composeを利用する際によく使うライブラリをまとめたbundlesを作成した
どのライブラリが含まれているかは `libs.versions.toml` の `bundles` を参照

composeを利用するためのライブラリをまとめたbundlesを作成

---

gradle/libs.versions.toml
wear/core/navigation/build.gradle.kts

wearにおいてSerializableを追加するためにlibs.version.tomlとbuild.gradleを変更
https://github.com/orgs/mayoi-design/projects/1/views/1?filterQuery=assignee%3ABakeryPanya&pane=issue&itemId=80726550

wearにおいてSerializableを追加するためにlibs.version.tomlとbuild.gradleを変更

---

gradle/libs.versions.toml
wear/app/build.gradle.kts
wear/features/settings/build.gradle.kts
wear/features/traveling/build.gradle.kts

`:phone` 用に `composeKit` を作ったので、`:wear` 用にも `wearComposeKit` を作った。
- https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=81982190

wearのmoduleでよく使うライブラリをまとめたbundleを作成

---

gradle/libs.versions.toml
phone/features/ranking/build.gradle.kts

タイトル通り
- https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=81982283

coil-ktを依存ライブラリに追加

---

wear/app/build.gradle.kts
wear/app/src/main/java/jp/ac/mayoi/maigocompass/presentation/MaigoNavigation.kt
wear/core/navigation/src/main/java/jp/ac/mayoi/wear/core/navigation/WearNavigation.kt

wear部分のnavigationを整備
https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=80726550

wear部分のnavigationの整備

---

phone/app/build.gradle.kts
phone/app/src/main/java/jp/ac/mayoi/maigocompass/NavHost.kt
phone/core/navigation/build.gradle.kts
phone/core/navigation/src/main/java/jp/ac/mayoi/core/navigation/AppNavigation.kt

PhoneのNavigationを整備しました。
ナビゲーション整備
https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=80726499
PhoneのAppNavigation.ktに、NavHostと各画面を表すSerializable Objectを作成しました。

PhoneのNavigationを整備

---

wear/features/waiting/build.gradle.kts
wear/features/waiting/src/main/java/jp/ac/mayoi/wear/features/waiting/WaitingScreen.kt

待機画面のUIにひな型の作成
- https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=80726648

待機画面のUIのひな型を作成

---

wear/core/resource/build.gradle.kts
wear/core/resource/src/main/java/jp/ac/mayoi/wear/core/resource/MaigoBotton.kt

previewを表示する際に必要なlibraryの追加
汎用性のあるボタンの作成(完成次第随時Pushします)
- https://github.com/orgs/mayoi-design/projects/1/views/1?pane=issue&itemId=81849717

Ryoka 1104/maigobotton

---

common/resource/build.gradle.kts

:common:resourceのbuild.gradle.ktsのnamespace設定が間違っていたのを修正

---

.github/workflows/android_lint.yaml
common/model/build.gradle.kts
common/resource/build.gradle.kts
gradle/libs.versions.toml
phone/app/build.gradle.kts
phone/core/application/build.gradle.kts
phone/core/navigation/build.gradle.kts
phone/core/resource/build.gradle.kts
phone/core/util/build.gradle.kts
phone/features/impressions/build.gradle.kts
phone/features/onboarding/build.gradle.kts
phone/features/ranking/build.gradle.kts
phone/features/share/build.gradle.kts
phone/features/traveling/build.gradle.kts
phone/model/build.gradle.kts
phone/repository/implementations/build.gradle.kts
phone/repository/interfaces/build.gradle.kts
phone/service/interfaces/build.gradle.kts
wear/app/build.gradle.kts
wear/core/navigation/build.gradle.kts
wear/core/resource/build.gradle.kts
wear/features/settings/build.gradle.kts
wear/features/traveling/build.gradle.kts
wear/features/waiting/build.gradle.kts
wear/repository/implementations/build.gradle.kts
wear/repository/interfaces/build.gradle.kts

slack-compose-lintsを導入

---

phone/core/application/build.gradle.kts
phone/core/application/src/main/java/jp/ac/mayoi/core/application/BaseApplication.kt
phone/model/build.gradle.kts
phone/model/src/main/java/jp/ac/mayoi/phone/model/AdapterResisterReach.kt
phone/model/src/main/java/jp/ac/mayoi/phone/model/RemoteImage.kt
phone/model/src/main/java/jp/ac/mayoi/phone/model/RemoteRanking.kt
phone/model/src/main/java/jp/ac/mayoi/phone/model/RemoteRankingArea.kt
phone/model/src/main/java/jp/ac/mayoi/phone/model/RemoteRankingAreaList.kt
phone/model/src/main/java/jp/ac/mayoi/phone/model/RemoteSpot.kt
phone/model/src/main/java/jp/ac/mayoi/phone/model/RemoteSpotList.kt
phone/service/interfaces/build.gradle.kts
phone/service/interfaces/src/main/java/jp/ac/mayoi/service/interfaces/HealthService.kt
phone/service/interfaces/src/main/java/jp/ac/mayoi/service/interfaces/ImageService.kt
phone/service/interfaces/src/main/java/jp/ac/mayoi/service/interfaces/RankingService.kt
phone/service/interfaces/src/main/java/jp/ac/mayoi/service/interfaces/SpotService.kt
phone/service/interfaces/src/main/java/jp/ac/mayoi/service/interfaces/UserService.kt

迷子コンパスAPIと通信するためのinterface、modelを整備した。  
JsonのSerializeなどは未テストなので、API完成前にテストしておいて、コケた後の修正に時間を食うのを減らしたいが、とりあえず別PRで対応する
- https://github.com/orgs/mayoi-design/projects/1/views/1?pane=issue&itemId=83331834

API通信用のinterfaceを整備 (未テスト)

---

gradle/libs.versions.toml
phone/app/src/main/AndroidManifest.xml
phone/core/application/build.gradle.kts
phone/core/application/secrets.gradle.kts
phone/features/onboarding/build.gradle.kts

タイトル通り
- https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=83444696

Google Maps Composeの導入

---

phone/app/build.gradle.kts
phone/app/src/development/AndroidManifest.xml
phone/app/src/development/java/jp/ac/mayoi/maigocompass/DevelopmentApplication.kt
phone/app/src/development/res/values/strings.xml
phone/app/src/main/AndroidManifest.xml
phone/app/src/production/AndroidManifest.xml
phone/app/src/production/java/jp/ac/mayoi/maigocompass/ProductionApplication.kt
phone/app/src/production/res/values/strings.xml
phone/core/resource/src/main/res/values/strings.xml

Build VariantとProduct Flavorを使ってマルチアプリビルドをできるようにした
- https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=83266400

Build Variantの切り替えでマルチアプリビルドをできるようにした

---

phone/core/resource/src/main/res/values/strings.xml
phone/features/traveling/src/main/java/jp/ac/mayoi/traveling/TravelingErrorScreen.kt

旅行中のネットワークエラーが起きたときの画面
https://github.com/orgs/mayoi-design/projects/1/views/1?pane=issue&itemId=84779925

旅行中のネットワークエラーが起きたときの画面

---

phone/model/src/main/java/jp/ac/mayoi/phone/model/MemoryAreaModel.kt
phone/model/src/main/java/jp/ac/mayoi/phone/model/UserMemory.kt
phone/repository/interfaces/build.gradle.kts
phone/repository/interfaces/src/main/java/jp/ac/mayoi/repository/interfaces/MemoryRepository.kt
phone/repository/interfaces/src/main/java/jp/ac/mayoi/repository/interfaces/RankingRepository.kt
phone/repository/interfaces/src/main/java/jp/ac/mayoi/repository/interfaces/TravelingRepository.kt

Repository類のinterfaceを作成した
- https://github.com/orgs/mayoi-design/projects/1/views/1?pane=issue&itemId=84837939

Repositoryのinterfaceを作成

---

gradle/libs.versions.toml
phone/app/build.gradle.kts
phone/app/src/development/java/jp/ac/mayoi/maigocompass/DevelopmentApplication.kt
phone/app/src/development/java/jp/ac/mayoi/maigocompass/mock/DevelopmentMemoryRepository.kt
phone/app/src/development/java/jp/ac/mayoi/maigocompass/mock/DevelopmentRankingRepository.kt
phone/app/src/development/java/jp/ac/mayoi/maigocompass/mock/DevelopmentTravelingRepository.kt
phone/core/application/src/main/java/jp/ac/mayoi/core/application/BaseApplication.kt
phone/model/src/main/java/jp/ac/mayoi/phone/model/RemoteSpot.kt
phone/model/src/main/java/jp/ac/mayoi/phone/model/UserMemory.kt

とりあえず現状でデータの入出力が決まっている画面についてはMockを作成した。  
共有画面などの、まだデータの概形が決まっていない点については作成していない。
- https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=84837939

開発ビルドで使用するMockのRepositoryを整備

---

phone/features/traveling/src/main/java/jp/ac/mayoi/traveling/TravelingLoadScreen.kt

旅行中のロード画面の作成
[
(https://github.com/orgs/mayoi-design/projects/1/views/1?sliceBy%5Bvalue%5D=%E3%82%B9%E3%83%9E%E3%83%9B%E3%82%A2%E3%83%97%E3%83%AA&pane=issue&itemId=85616568)

ロード中の画面の作成

---

common/model/build.gradle.kts
common/resource/build.gradle.kts
phone/app/build.gradle.kts
phone/core/application/build.gradle.kts
phone/core/navigation/build.gradle.kts
phone/core/resource/build.gradle.kts
phone/core/util/build.gradle.kts
phone/features/impressions/build.gradle.kts
phone/features/onboarding/build.gradle.kts
phone/features/ranking/build.gradle.kts
phone/features/share/build.gradle.kts
phone/features/traveling/build.gradle.kts
phone/model/build.gradle.kts
phone/repository/implementations/build.gradle.kts
phone/repository/interfaces/build.gradle.kts
phone/service/interfaces/build.gradle.kts
wear/app/build.gradle.kts
wear/core/application/build.gradle.kts
wear/core/navigation/build.gradle.kts
wear/core/resource/build.gradle.kts
wear/features/settings/build.gradle.kts
wear/features/traveling/build.gradle.kts
wear/features/waiting/build.gradle.kts
wear/repository/implementations/build.gradle.kts
wear/repository/interfaces/build.gradle.kts

minSdkを28から30に変更

---

gradle/libs.versions.toml
wear/app/build.gradle.kts
wear/app/src/main/java/jp/ac/mayoi/maigocompass/presentation/MaigoNavigation.kt
wear/app/src/main/java/jp/ac/mayoi/maigocompass/presentation/MainActivity.kt
wear/features/waiting/build.gradle.kts
wear/features/waiting/src/main/java/jp/ac/mayoi/wear/features/waiting/WaitingScreenViewModel.kt
wear/features/waiting/src/main/java/jp/ac/mayoi/wear/features/waiting/WaitingSwipe.kt

横スクロール済みの待機画面を作成したViewModelを用いてMaigoNavigationと連携した
https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=80726648
横スクロール済みの待機画面を作成したViewModelを用いてMaigoNavigationと連携した。また実機でテストも行った

ViewModelの作成とMaigoNavigationとの連携

---

common/model/build.gradle.kts
common/resource/build.gradle.kts
phone/app/build.gradle.kts
phone/core/application/build.gradle.kts
phone/core/datastore/build.gradle.kts
phone/core/navigation/build.gradle.kts
phone/core/resource/build.gradle.kts
phone/core/util/build.gradle.kts
phone/features/impressions/build.gradle.kts
phone/features/onboarding/build.gradle.kts
phone/features/ranking/build.gradle.kts
phone/features/share/build.gradle.kts
phone/features/traveling/build.gradle.kts
phone/model/build.gradle.kts
phone/repository/implementations/build.gradle.kts
phone/repository/interfaces/build.gradle.kts
phone/service/interfaces/build.gradle.kts
wear/app/build.gradle.kts
wear/core/application/build.gradle.kts
wear/core/navigation/build.gradle.kts
wear/core/resource/build.gradle.kts
wear/features/settings/build.gradle.kts
wear/features/traveling/build.gradle.kts
wear/features/waiting/build.gradle.kts
wear/repository/implementations/build.gradle.kts
wear/repository/interfaces/build.gradle.kts

sdkを35にupdate

---

phone/app/src/development/java/jp/ac/mayoi/maigocompass/mock/DevelopmentTravelingRepository.kt
phone/core/util/src/main/java/jp/ac/mayoi/core/util/SpotCard.kt
phone/features/ranking/src/main/java/jp/ac/mayoi/ranking/RankingList.kt
phone/features/ranking/src/main/java/jp/ac/mayoi/ranking/RankingSuccessScreen.kt
phone/features/traveling/src/main/java/jp/ac/mayoi/traveling/TravelingScreen.kt
phone/features/traveling/src/main/java/jp/ac/mayoi/traveling/TravelingSpotScreen.kt
phone/model/src/main/java/jp/ac/mayoi/phone/model/LocalSpot.kt
phone/repository/interfaces/src/main/java/jp/ac/mayoi/repository/interfaces/TravelingRepository.kt

LocalSpotのメンバとTravelingRepositoryの定義を修正

---

phone/core/application/build.gradle.kts
phone/core/application/src/main/java/jp/ac/mayoi/core/application/BaseApplication.kt
phone/features/traveling/build.gradle.kts
phone/features/traveling/src/main/java/jp/ac/mayoi/traveling/TravelingViewModel.kt

TravelingViewModelの作成
(https://github.com/orgs/mayoi-design/projects/1/views/1?sliceBy%5Bvalue%5D=%E3%82%B9%E3%83%9E%E3%83%9B%E3%82%A2%E3%83%97%E3%83%AA&pane=issue&itemId=87923766)

TravelingViewModelの作成

---

phone/core/application/build.gradle.kts
phone/core/application/src/main/java/jp/ac/mayoi/core/application/BaseApplication.kt
phone/model/src/main/java/jp/ac/mayoi/phone/model/LocalSpot.kt
phone/repository/implementations/build.gradle.kts
phone/repository/implementations/src/main/java/jp/ac/mayoi/repository/implementations/TravelingRepositoryImpl.kt
phone/service/interfaces/src/main/java/jp/ac/mayoi/service/interfaces/SpotService.kt

TravelingRepositoryImplを実装しました
TravelingRepositoryの実装 (スマホ)
https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=87506852

 TravelingRepositoryの実装 (スマホ)

---

phone/app/src/main/res/xml/wear.xml
phone/core/application/build.gradle.kts
phone/core/application/src/main/java/jp/ac/mayoi/core/application/BaseApplication.kt
wear/app/build.gradle.kts
wear/app/src/main/res/values/wear.xml
wear/core/application/src/main/java/jp/ac/mayoi/wear/core/application/BaseApplication.kt

https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=87584310
- close #n
|        |       |

wearとphoneの繋ぎこみの準備処理

---

phone/features/traveling/src/main/java/jp/ac/mayoi/traveling/TravelingScreen.kt
phone/features/traveling/src/main/java/jp/ac/mayoi/traveling/TravelingViewModel.kt

スポットが表示されているときにロード画面を表示しないようにする

Load画面を表示するときとしないときの場合分け

---

wear/features/traveling/src/main/java/jp/ac/mayoi/wear/features/traveling/TravelingRoot.kt
wear/features/traveling/src/main/java/jp/ac/mayoi/wear/features/traveling/TravelingScreen.kt

概要はタイトル通り
- 不要になったtodoコメントが残っていたので削除
- `TravelingScreen.kt` の中身が全てpublicになっていたので、privateにできるところはprivateにした

Watch旅行中画面のコメントや可視性に関連する細かなリファクタ

---

wear/features/traveling/src/main/java/jp/ac/mayoi/wear/features/traveling/TravelingScreen.kt

UIに表示する距離をfocusingから取得するのをやめた

---

wear/features/traveling/src/main/java/jp/ac/mayoi/wear/features/traveling/TravelingScreen.kt

[リリース用] 旅行中画面のレスポンシブ対応

---

phone/core/resource/src/main/java/jp/ac/mayoi/core/resource/Colors.kt
phone/features/memory/build.gradle.kts
phone/features/memory/src/main/java/jp/ac/mayoi/memory/graph/MemoryGraph.kt
phone/features/memory/src/main/java/jp/ac/mayoi/memory/graph/MemoryPieChart.kt
phone/model/build.gradle.kts
phone/model/src/main/java/jp/ac/mayoi/phone/model/ChartEntry.kt
phone/model/src/main/java/jp/ac/mayoi/phone/model/ChartModel.kt

思い出画面で利用する円グラフを表示する機能を追加した。まだクリックや、旅行回数の表示などの機能はない。
- 円グラフのデータを抽象化するPieChartEntryとPieChartModelを追加した
- 上記の2 data classから円グラフを表示する機能を作成した

円グラフを表示できる機能を追加

---

phone/core/resource/src/main/java/jp/ac/mayoi/core/resource/TextStyle.kt
phone/features/memory/src/main/java/jp/ac/mayoi/memory/graph/MemoryGraph.kt
phone/features/memory/src/main/java/jp/ac/mayoi/memory/graph/MemoryPieChart.kt
phone/features/memory/src/main/java/jp/ac/mayoi/memory/graph/MemoryPieChartInfo.kt

円グラフをクリックしてエリアの情報を閲覧するような機能を実装した。

円グラフの縁をクリックできるような実装を追加

---

phone/features/memory/src/main/java/jp/ac/mayoi/memory/graph/MemoryPieChart.kt

おもいで画面のグラフの選択したエントリの伸縮にアニメーションがつくようにした
