mayoi-design/maigo_compass_android

phone/app/src/main/java/jp/ac/mayoi/maigocompass/MainActivity.kt

@koae0522 と EdgeToEdge 対応はしないということを決めたので、MainActivityからenableEdgeToEdgeを削除した
- https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=81154287
- `:phone:app` の `MainActivity` から `enableEdgeToEdge` を削除

enableEdgeToEdgeを削除

---

phone/core/util/build.gradle.kts
phone/core/util/src/main/java/jp/ac/mayoi/core/util/Buttons.kt

FigmaのDesign Templateに合わせて、`phone` 側で利用するMaigoButtonを作成した。
- https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=81853047

maigobuttonを作った

---

wear/core/resource/src/main/java/jp/ac/mayoi/wear/core/resource/Colors.kt
wear/core/resource/src/main/java/jp/ac/mayoi/wear/core/resource/MaigoBotton.kt

Maigobuttonで作成したボタンの色をデザイン案であるテンプレートの色に合わせる
https://github.com/orgs/mayoi-design/projects/1/views/1?filterQuery=priority%3A%22%E3%81%99%E3%81%90%E3%82%84%E3%82%8B%22&pane=issue&itemId=81849717
デフォルトで設定されていたボタンの色をテンプレートで指定されている色に変更する

MaigoButtonで作成したボタンの色をテンプレートの色に合わせる

---

phone/features/traveling/build.gradle.kts
phone/features/traveling/src/main/java/jp/ac/mayoi/traveling/TravelingScreen.kt

旅行中画面の近くにおすすめスポットがない時に表示する画面の中央部分の作成 
https://github.com/orgs/mayoi-design/projects/1/views/1?pane=issue&itemId=80902595

旅行中画面の近くにスポットがない場合の中心画面の作成

---

build.gradle.kts
phone/features/ranking/build.gradle.kts
phone/features/ranking/src/main/java/jp/ac/mayoi/ranking/Button.kt
phone/features/ranking/src/main/java/jp/ac/mayoi/ranking/RankingButton.kt

ランキング画面のボタン要素の作成、それに伴いButton.ktの作成。
2024/10/23 追記
Button.ktをRankingButton.ktに名前変更しました。
https://github.com/orgs/mayoi-design/projects/1/views/1?pane=issue&itemId=81905765
phone\features\ranking\src\main\java\jp\ac\mayoi\rankingにButton.ktを新規に作成。
Button.ktではランキング画面のボタン要素の作成をしている。
ボタンが2個以上の時、ボタンの選択状態によって問題なくボタンの色が変更されるかを確認した。
line17)val buttonLabels = listOf("エリア名")　※PR時
listOfの部分を複数個の項目に変えてボタンが複数表示されるようにして、ボタン色の切り替えができるように確認した。
ex.) val buttonLabels = listOf("エリア名","エリア名","名前がちょっと長いエリア名")

ランキング画面のボタン要素の作成

---

phone/core/resource/src/main/res/values/strings.xml
phone/features/traveling/src/main/java/jp/ac/mayoi/traveling/TripCancelButton.kt

旅行中断ボタンの作成

---

wear/features/waiting/build.gradle.kts
wear/features/waiting/src/main/java/jp/ac/mayoi/wear/features/waiting/WaitingScreen.kt

Watch側の待機画面の実装を行った。またボタンを押した後の処理も行っている。
https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=80726648
デザイン原案を基に文章とボタンを作成し、ボタンを押した後の処理についてはボタンを非表示にしてから文章を表示している
https://github.com/user-attachments/assets/a8bd82fd-14d8-468f-8a8f-9200e06d3209

Watch内の目的地設定画面を実装

---

phone/core/resource/src/main/res/values/strings.xml
phone/features/traveling/src/main/java/jp/ac/mayoi/traveling/TravelingScreen.kt
phone/features/traveling/src/main/java/jp/ac/mayoi/traveling/TripCancelButton.kt

旅行中の近くにスポットがない場合の画面のボトム部分の作成
https://github.com/orgs/mayoi-design/projects/1/views/1?pane=issue&itemId=83888218

旅行中の近くにスポットがない場合の画面のボトム部分の作成

---

common/resource/src/main/java/jp/ac/mayoi/common/resource/CommonColors.kt
wear/core/resource/src/main/java/jp/ac/mayoi/wear/core/resource/Colors.kt
wear/features/waiting/src/main/java/jp/ac/mayoi/wear/features/waiting/AppSettingButton.kt

待機画面を横にスワイプした際のアプリ設定ボタンを実装
https://github.com/orgs/mayoi-design/projects/1/views/1?pane=issue&itemId=80726648
新規にAppSettingButton.ktを作成し、アプリ設定ボタンを作成
またボタンの色が異なるためColors.kt,CommonColors.ktにその定義を追加

待機画面のアプリ設定ボタンの作成

---

phone/core/util/src/main/java/jp/ac/mayoi/core/util/LoadState.kt

ネットワークからデータをロードしている際の状態を表す`sealed class`を実装した。
実際に使う際は以下のように使う
```kotlin
@Composable
internal fun なんかロードする画面(
nantokaState: LoadingState<NantokaModel>,
) {
when(nantokaState) {
is LoadState.Error {
// エラー時の画面、処理を書く。
// 一応valueの値をnullableだけど参照することもできる。
}
is LoadState.Loading {
// ロード中の画面、処理を書く
// 一応valueの値をnullableだけど参照することもできる。
}
is LoadState.Success {
// ロード完了後の画面、処理を書く。
}
}
}
```
- https://github.com/orgs/mayoi-design/projects/1/views/1?pane=issue&itemId=85320192

LoadStateを実装

---

phone/core/application/src/main/java/jp/ac/mayoi/core/application/BaseApplication.kt

初回起動時というか、ストレージに有効なユーザーIDが記録されていなかったら生成するようにした。
- https://github.com/orgs/mayoi-design/projects/1/views/1?pane=issue&itemId=84937383

初回起動時にユーザーIDを生成する処理を実装

---

phone/core/resource/src/main/res/values/strings.xml
phone/features/traveling/src/main/java/jp/ac/mayoi/traveling/TravelingScreen.kt

迷子コンパスの統一仕様に基づいて、旅行中にスポットを登録できないように修正した。
比較画像については、左のスクリーンショットが昔のもののため、旅行を中断ボタンが表示されていない状態になっている。
- https://github.com/orgs/mayoi-design/projects/1/views/1?pane=issue&itemId=84820973
- 旅行中にスポットがない場合に表示していたスポットを登録ボタンを消した
- 同時に、文言を修正
|![image](https://github.com/user-attachments/assets/426bab8c-8231-42cb-82f1-3ca11f3e0eed)|![image](https://github.com/user-attachments/assets/48053512-d259-4ce0-9725-25e4c942a4a3)|

旅行中にスポットを登録できないように仕様を修正

---

phone/features/ranking/build.gradle.kts
phone/features/ranking/src/main/java/jp/ac/mayoi/ranking/RankingList.kt
phone/features/ranking/src/main/java/jp/ac/mayoi/ranking/RankingLoading.kt

RankingListとRankingLoadingの画面を作成
ランキング画面のリスト表示を実装する
https://github.com/orgs/mayoi-design/projects/1/views/1?pane=issue&itemId=84820419
ランキング画面のリストを作成しました
RankingListにリストを、RankingLoadingにロード中の画面を作成

RankingListとRankingLoadingの画面を作成

---

phone/core/resource/src/main/res/drawable/location_fill.xml
phone/core/resource/src/main/res/drawable/position_set.xml
phone/features/onboarding/src/main/java/jp/ac/mayoi/onboarding/OnboardingScreen.kt

CameraPositionStateの位置がずれていたわけではなく、GoogleMapsComposeに設定したcontentPaddingの影響で、ScaffoldのContentの中心座標とズレが発生しているように見えていた。  
具体的には、GoogleMapsCompose内の座標系が右に`spacingDouble`、上に`96.dp`ずれていたので、contentPaddingを右と上にもつけるようにした。  
これにより、GoogleMaps上に書かれるwidgetは上下左右設定した余白だけ空いて表示されることになるが、実機で確認した感じ、Map上の建物の情報などはContentPaddingの影響を受けないようだった + このアプリでは他にMap上に表示するMarkerなどがないため、これでも問題ないと判断した。

ScaffoldのContentの中心とGoogleMapsCompose内の中心がずれている問題を修正

---

phone/features/traveling/build.gradle.kts
phone/features/traveling/src/main/java/jp/ac/mayoi/traveling/TravelingSpotScreen.kt

旅行中にスポットリストを表示したときの画面の作成
https://github.com/orgs/mayoi-design/projects/1/views/1?sliceBy%5Bvalue%5D=%E3%82%B9%E3%83%9E%E3%83%9B%E3%82%A2%E3%83%97%E3%83%AA&pane=issue&itemId=86165669

旅行中のスポットリスト画面の作成

---

phone/app/build.gradle.kts
phone/app/src/main/java/jp/ac/mayoi/maigocompass/NavHost.kt
phone/core/application/build.gradle.kts
phone/core/application/src/main/java/jp/ac/mayoi/core/application/BaseApplication.kt
phone/core/resource/src/main/res/drawable/position_set.xml
phone/features/onboarding/src/main/java/jp/ac/mayoi/onboarding/OnboardingScreen.kt
phone/features/onboarding/src/main/java/jp/ac/mayoi/onboarding/OnboaringViewModel.kt

目的地を設定できるよう、画面の中心の緯度経度をviewModelに渡せるようにした。
旅行開始画面で緯度経度を指定できるようにする
https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=84818760
目的地を設定できるよう、画面の中心の緯度経度をcameraPositionState.position.targetから取得し、viewModelに渡せるようにした。
Iconを使って中心を指すマーカーを設置した。
目的地を設定ボタンを押したらtravelingScreenに遷移できるようnavHostを設定した。

目的地を設定できるよう、画面の中心の緯度経度をviewModelに渡せるようにした

---

phone/features/ranking/src/main/java/jp/ac/mayoi/ranking/RankingSuccessScreen.kt

RankingSuccessScreenを作成した。これはランキングを参照可能なエリアを取得できたら表示する画面。
画面の上にはエリア選択ボタンが表示されており、その下にロード中のぐるぐるか、ランキングのリストが表示される。
https://github.com/orgs/mayoi-design/projects/1/views/1?pane=issue&itemId=86466682

RankingSuccessScreenの作成

---

wear/repository/implementations/src/main/java/jp/ac/mayoi/wear/repository/implementations/LocationRepositoryImpl.kt
wear/repository/implementations/src/test/kotlin/jp/ac/mayoi/wear/repository/implementations/LocationRepositoryImplTest.kt

現在向いている方位角から目的地までの偏角を取得するgetBearingが誤った値を返していた。  
一度 [処理を明文化](https://scrapbox.io/PBL2024mayoi/%E7%9B%AE%E7%9A%84%E5%9C%B0%E3%81%AE%E6%96%B9%E5%90%91%E3%81%AF%E4%BB%8A%E3%81%AE%E5%90%91%E3%81%84%E3%81%A6%E3%81%84%E3%82%8B%E6%96%B9%E5%90%91%E3%81%8B%E3%82%89%E4%BD%95%E5%BA%A6%E3%81%9A%E3%82%8C%E3%81%A6%E3%81%84%E3%82%8B%E3%81%8B%EF%BC%9F) し、そのとおりになるよう実装を修正した。
- https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=87969844
- https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=88224619
- getBearingのテストを書いた
- 元のままではUnitテストで動かせなかったので、internalなメソッドを作成し、ラッピングして利用するようにした。
- Scrapboxに処理のドキュメントを書いた
- getBearingの実装を修正した
- 任意の目的地、おすすめスポットに対して、正しいbearingを返すことができる。
- ただし、Watchが取得する方位角は正しいものとする。

getBearingが間違った値を返している問題を修正

---

phone/app/src/main/java/jp/ac/mayoi/maigocompass/NavHost.kt
phone/app/src/main/java/jp/ac/mayoi/maigocompass/RootScreen.kt

ボトムバーを出す画面と出さない画面を分けました
bottomBarを表示する画面と表示しない画面を分ける
https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=87349970
currentDestinationによって、onboard,ranking,memory画面の時だけボトムバーを表示するようにしました。
確認のため、travelingScreenにテキストを書きました。

bottomNavigationを出す画面と出さない画面を分けた

---

wear/features/traveling/src/main/java/jp/ac/mayoi/wear/features/traveling/TravelingScreen.kt

おすすめスポットの距離とテキストの表示方法の変更した
https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=83886317
以前実装したおすすめスポットを表示した際のテキストの表示方法をTravelingViewModel内から持ってくるようにする

おすすめスポットの距離とテキストの表示方法の変更

---

common/resource/src/main/java/jp/ac/mayoi/common/resource/Strings.kt
phone/app/build.gradle.kts
phone/app/src/main/AndroidManifest.xml
phone/app/src/main/java/jp/ac/mayoi/maigocompass/NavHost.kt
phone/features/traveling/build.gradle.kts
phone/features/traveling/src/main/AndroidManifest.xml
phone/features/traveling/src/main/java/jp/ac/mayoi/traveling/TravelingScreen.kt
phone/features/traveling/src/main/java/jp/ac/mayoi/traveling/TravelingViewModel.kt
wear/core/resource/src/main/java/jp/ac/mayoi/wear/core/resource/Strings.kt
wear/features/traveling/build.gradle.kts
wear/features/traveling/src/main/java/jp/ac/mayoi/wear/features/traveling/TravelingViewModel.kt
wear/service/build.gradle.kts
wear/service/src/main/java/jp/ac/mayoi/wear/service/LocationService.kt

旅行中に定期的におすすめスポットをAPIに訪ねに行く処理を書いた
- https://github.com/orgs/mayoi-design/projects/1/views/1?pane=issue&itemId=84822600
- `:wear:service:LocationService` を `:phone`でも共通して使うようにした
- 位置情報更新の頻度を変えられるようにした
- LocationServiceがServiceのライフサイクルを超えて位置情報を更新している問題を修正
- 旅行中画面でおすすめスポットをポーリングする処理を書いた
- 適当に移動してみて、現在の緯度経度が正常に更新されること
- 現在の緯度経度に基づいたおすすめスポットが取得できること

旅行中画面でおすすめスポットをポーリングする処理を実装

---

wear/features/traveling/build.gradle.kts
wear/features/traveling/src/main/java/jp/ac/mayoi/wear/features/traveling/TravelingRoot.kt
wear/features/traveling/src/main/java/jp/ac/mayoi/wear/features/traveling/TravelingScreen.kt

おすすめスポットと目的地画面を遷移できるようにする
https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=83886317
三角形を押すと「おすすめスポットの画面と目的地の画面」が遷移するようにつなげる
|        |       |

おすすめスポットと目的地画面を遷移できるようにする

---

wear/features/traveling/src/main/java/jp/ac/mayoi/wear/features/traveling/TravelingScreen.kt

Watch旅行中画面に遷移した際に、目的地までの距離が10000kmを超えた状態で表示されることがある。これは、位置情報が取得できるまで現在地が北緯0°、東経0°にあるためであるが、位置情報が取得できた後もこの距離が更新されないバグが存在する。  
原因はUIがfocusingから表示用の距離を取得していること。  
これにより、今回の修正対象の既知のバグだけでなく、いくら移動してもスポットを選択した時の残り距離から更新されないと言うバグも修正されることになる。  
isHeadingDestinationがtrueであろうとfalseであろうとfocusingのdistance値を参照してはいけない。
- https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=89491657
- 概要通り
- 旅行中画面に遷移したのち、何も操作せずとも距離の表示は正常値に戻るか

旅行中画面で、目的地までの距離が10000km越えから更新されないことがある

---

wear/features/traveling/src/main/java/jp/ac/mayoi/wear/features/traveling/TravelingScreen.kt

今までWatch旅行中画面はpaddingなどを用いてアラインメントされていた。そのため、Watch 2 と 3 のデバイス間の解像度差異を吸収することができていなかった。  
このPRでは、paddingによる位置調整をやめ、ColumnやRowを用いたアラインメントを行うように変更した。
- https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=89503791
- 共通化すべきコンポーネントを共通化した
- レイアウトの中で、paddingを用いて位置合わせを行なっているコンポーネントをLayoutによる位置合わせに変更した
- Previewを行えるように関数の切り分けを行い、Previewを作成した。
- デバイス間で表示に大きな差が発生しないようになっているか
上が Watch 2。下が Watch 3。  
方位角の違いは単にセンサーの差異なので、気にしないで大丈夫
|    ![watch2_before](https://github.com/user-attachments/assets/b42e9bfe-5bb1-43f6-bf9c-2b11c3d9279a)    |    ![watch2_after_retake](https://github.com/user-attachments/assets/3c16e408-db49-48ed-8bd3-ef699d9f6efa)   |
|    ![watch3_before](https://github.com/user-attachments/assets/0a52d54f-412d-42ad-b893-bc18751103e4)    | …

Watch旅行中画面のレスポンシブ対応を行なった

---

common/model/src/main/java/jp/ac/mayoi/common/model/Destination.kt
common/resource/src/main/java/jp/ac/mayoi/common/resource/Strings.kt
phone/app/src/main/java/jp/ac/mayoi/maigocompass/NavHost.kt
phone/core/application/src/main/java/jp/ac/mayoi/core/application/BaseApplication.kt
phone/core/resource/src/main/java/jp/ac/mayoi/core/resource/Strings.kt
phone/features/onboarding/build.gradle.kts
phone/features/onboarding/src/main/java/jp/ac/mayoi/onboarding/OnboaringViewModel.kt
phone/features/traveling/src/main/java/jp/ac/mayoi/traveling/TravelingViewModel.kt
wear/app/src/main/java/jp/ac/mayoi/maigocompass/presentation/MaigoNavigation.kt
wear/core/application/build.gradle.kts
wear/core/application/src/main/java/jp/ac/mayoi/wear/core/application/BaseApplication.kt
wear/core/navigation/src/main/java/jp/ac/mayoi/wear/core/navigation/WearNavigation.kt
wear/core/resource/src/main/java/jp/ac/mayoi/wear/core/resource/Strings.kt
wear/features/traveling/src/main/java/jp/ac/mayoi/wear/features/traveling/TravelingRoot.kt
wear/features/traveling/src/main/java/jp/ac/mayoi/wear/features/traveling/TravelingViewModel.kt
wear/features/waiting/build.gradle.kts
wear/features/waiting/src/main/java/jp/ac/mayoi/wear/features/waiting/WaitingScreenViewModel.kt
wear/features/waiting/src/main/java/jp/ac/mayoi/wear/features/waiting/WaitingSwipe.kt
wear/repository/implementations/build.gradle.kts
wear/repository/implementations/src/main/java/jp/ac/mayoi/wear/repository/implementations/TravelingRepositoryImpl.kt
wear/repository/interfaces/src/main/java/jp/ac/mayoi/wear/repository/interfaces/TravelingRepository.kt

- PhoneからWatchに目的地を送信する機能を実装した
- まだ不完全なので、両方のActivityがTopに載っている必要がある
- 今後可能なタイミングでIntentやServiceを用いた送信処理に移行する
- https://github.com/orgs/mayoi-design/projects/1?pane=issue&itemId=90321120
- OnboardingScreenから目的地を決定した時、Watch側で正常にTripNavigationに遷移できるか
- 画面遷移前のブロッキングは正常に行われているか
- 状態は競合していないか

PhoneからWatchに旅行開始時の目的地を送信する機能を付与した

---

phone/features/memory/src/main/java/jp/ac/mayoi/memory/graph/MemoryGraph.kt
phone/features/memory/src/main/java/jp/ac/mayoi/memory/graph/MemoryPieChart.kt

おもいで画面の円グラフで、選択されたエントリに応じて、対応するエントリのタップ可能領域が拡大し、色付きの縁も大きくなるようにした。

円グラフの中で選択したエントリが拡大するようにした

---

phone/model/src/main/java/jp/ac/mayoi/phone/model/enums/ServiceArea.kt
phone/model/src/main/java/jp/ac/mayoi/phone/model/interfaces/StringEnum.kt
phone/model/src/test/kotlin/jp/ac/mayoi/phone/model/enums/ServiceAreaParseTest.kt

サーバーとクライアントではuniqueな文字列を用いたenumをやり取りする。Http通信上ではただのstringであるが、クライアント側ではKotlinのenumとして扱うことによるコード上のメリットも存在する。
そこで、文字列からKotlin enumへの変換処理を行うような `StringEnumAdapter` と `StringEnum` を実装した。

サーバーとやり取りする文字列enumをKotlinのenumに変換する処理を実装
